<a href="https://colab.research.google.com/github/Dohun-Im/python/blob/master/coloab_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('hh')

hh


In [2]:
from google.colab import drive

In [3]:
drive.mount('/content/drive')

Mounted at /content/drive


In [8]:
import pandas as pd
import numpy as np


In [7]:
df = pd.read_csv('/content/drive/MyDrive/csv_data/crime.csv',encoding='cp949')
df

관서명  살인 발생  살인 검거  강도 발생  강도 검거  강간 발생  강간 검거  절도 발생  절도 검거  폭력 발생  폭력 검거
0    중부서      2      2      3      2    105     65  1,395    477  1,355  1,170
1    종로서      3      3      6      5    115     98  1,070    413  1,278  1,070
2   남대문서      1      0      6      4     65     46  1,153    382    869    794
3   서대문서      2      2      5      4    154    124  1,812    738  2,056  1,711
4    혜화서      3      2      5      4     96     63  1,114    424  1,015    861
5    용산서      5      5     14     14    194    173  1,557    587  2,050  1,704
6    성북서      2      2      2      1     86     71    953    409  1,194  1,015
7   동대문서      5      5     13     13    173    146  1,981    814  2,548  2,227
8    마포서      8      8     14     10    294    247  2,555    813  2,983  2,519
9   영등포서     14     12     22     20    295    183  2,964    978  3,572  2,961
10   성동서      4      4      9      8    126    119  1,607    597  1,612  1,395
11   동작서      5      5      9      5    285    139  1,865    661  1,910  1,587
12   광진서      4      4     14     26    240    220  3,026  1,277  2,625  2,180
13   서부서      2      2      2      1     70     59    819    293  1,192  1,038
14   강북서      7      8     14     13    153    126  1,434    618  2,649  2,348
15   금천서      3      4      6      6    151    122  1,567    888  2,054  1,776
16   중랑서     13     12     11      9    187    148  2,135    829  2,847  2,407
17   강남서      3      3     15     12    300    225  2,411    984  2,465  2,146
18   관악서      9      8     12     14    320    221  2,706    827  3,298  2,642
19   강서서      7      8     13     13    262    191  2,096  1,260  3,207  2,718
20   강동서      4      3      6      8    156    123  2,366    789  2,712  2,248
21   종암서      3      3      3      3     64     53    832    332  1,015    840
22   구로서      8      6     15     11    281    164  2,335    889  3,007  2,432
23   서초서      7      4      8      5    334    193  1,982    905  1,852  1,607
24   양천서      3      5      6      3    120    105  1,890    672  2,509  2,030
25   송파서     11     10     13     10    220    178  3,239  1,129  3,295  2,786
26   노원서     10     10      7      7    197    121  2,193    801  2,723  2,329
27   방배서      1      2      1      1     59     56    653    186    547    491
28   은평서      1      1      7      5     96     82  1,095    418  1,461  1,268
29   도봉서      3      3      9     10    102    106  1,063    478  1,487  1,303
30   수서서     10      7      6      6    149    124  1,439    666  1,819  1,559

In [11]:
df = pd.DataFrame({
                  'name':['hong','park'], 
                   'age': [10,20]
                   })
df

name  age
0  hong   10
1  park   20

In [12]:
# DF의 구성요소 -> Index 와 column

df.index
# RangeIndex 는 클래스임 -> 즉 DF는 RangeIndex 객체와 행렬의 조합

RangeIndex(start=0, stop=2, step=1)

In [13]:
df.values

array([['hong', 10],
       ['park', 20]], dtype=object)

In [15]:
#컬럼 불러오기 (같은 기능)
df.name
df['name']

0    hong
1    park
Name: name, dtype: object

In [20]:
df.name.index
df.name.values # 리스트 형태가 아님 객체형태!

array(['hong', 'park'], dtype=object)

In [22]:
df.name.values.tolist() # 클래스 객체형태를 리스트로 변환 (언래핑)

['hong', 'park']

In [36]:
#튜플형태로 DF만들기
df2 = pd.DataFrame(data= [['hong',10], ['park',20]], columns = ['name','age'])
df2

name  age
0  hong   10
1  park   20

In [32]:
df2.dtypes

name    object
age      int64
dtype: object

In [33]:
df2.age.astype(float) 
#astype 는 원본(df2)자체를 바꾸지는 않음 => '비파괴함수'
#df2를 다시 쳐보면 int64로 그대로임
#df2를 다시 변수에 대입하면 유지됨

0    10.0
1    20.0
Name: age, dtype: float64

In [37]:
df2.age = df2.age.astype(float) 
df2

name   age
0  hong  10.0
1  park  20.0

In [38]:
df2.age = df2.age.astype(int) 
df2

name  age
0  hong   10
1  park   20

In [39]:
df2.dtypes

name    object
age      int64
dtype: object

In [40]:
df2.describe()

age
count   2.000000
mean   15.000000
std     7.071068
min    10.000000
25%    12.500000
50%    15.000000
75%    17.500000
max    20.000000

In [41]:
type(df2['name'])

pandas.core.series.Series

In [42]:
df2['name']

0    hong
1    park
Name: name, dtype: object

In [44]:
df2.name.index

RangeIndex(start=0, stop=2, step=1)

In [45]:
df2.name.values

array(['hong', 'park'], dtype=object)

In [46]:
type(df2['name'].values)

numpy.ndarray

In [47]:
mask = np.zeros(5)
mask

array([0., 0., 0., 0., 0.])

In [48]:
mask2 = np.zeros((3,4))
mask2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
arr2 = np.array([
    [1,2,3],[4,5,6]],
    dtype=np.float64
)
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [56]:
arr3 = np.array([[1,2,3],[2,3,4]]
                ,dtype=int)

arr3

array([[1, 2, 3],
       [2, 3, 4]])

In [57]:
arr2 + arr3 

array([[ 2.,  4.,  6.],
       [ 6.,  8., 10.]])

In [58]:
arr2 * arr3

array([[ 1.,  4.,  9.],
       [ 8., 15., 24.]])